### ISSUE TITLE
Logout functionality

### ISSUE THREAD

**Issue by saurabh-p** [sirkitree/angular-directive.g-signin#26]
How to create logout feature with this?

**Comment by phw** [comment]
Maybe this will help:
https://developers.google.com/+/web/signin/sign-out

**Comment by Abhivendra** [comment]
Not working , please provide some more details.

**Comment by sbatbayar** [comment]
I using this to do this.
gapi.auth.signOut()

**Comment by cmichaelis** [comment]
Alas, it doesn't work for me. gapi.auth.signOut is a valid function, and when run it produces no errors; but neither does it do anything. Next time the page loads, the $scope.$on('event:google-plus-signin-success' event instantly occurs with the account I had been logged in with. Anyone else see the same thing and have a fix?
