### ISSUE TITLE
how can i get the email id of the user after logged in. May i know which variable has it ? 

### ISSUE THREAD

**Issue by vikasmd** [sirkitree/angular-directive.g-signin#37]
how can i get the email id of the user after logged in. May i know which variable has it ?

**Comment by shrutiLetsgomo** [comment]
Check out the link
https://github.com/sirkitree/angular-directive.g-signin/issues/27

**Comment by vikasmd** [comment]
Thanks alot

---- On Mon, 08 Jun 2015 23:37:58 +0530 shrutiLetsgomo &lt;notifications@github.com&gt; wrote ---- 

Check out the link
 #27
