### ISSUE TITLE
Token expires too quickly. How do I set the token expiration or request a new one?

### ISSUE THREAD

**Issue by naphtul** [sirkitree/angular-directive.g-signin#51]
I have implemented this very useful directive in my application.
However, if I leave the app open for a while, the next server request tells me that the token is invalid/expired.
How do I request a longer-lasting token?
Alternatively, how do I refresh the token before every request to my server (that will authenticate its validity against Google servers)?

**Comment by docsuleman** [comment]
did you find any solution?

**Comment by naphtul** [comment]
My solution was to use "access" token instead of the "id" token.
You can read about it here.
https://developers.google.com/identity/protocols/OAuth2UserAgent#formingtheurl
Pay attention to the differences between the token types.
