### ISSUE TITLE
ECONFLICT Unable to find suitable version for angular

### ISSUE THREAD

**Issue by crazyabdul** [sirkitree/angular-directive.g-signin#52]
I kept getting this `ECONFLICT Unable to find suitable version for angular` error when i tried installing `angular-directive.g-sign` through bower. So I took a look at your code and realised it was dependent on an older version of angular. I decided to bypass bower, copy the `google-plus-signin.js` file and part of the demo file to my project before it worked. 

I think making the directive compatible with angular 1.5.x or newer would fix the bower issue and prevent future frustrations

**Comment by sirkitree** [comment]
Thanks for the report. I don't use angular much theses days so my time
maintaining this is sparse to say the least. Happy to review patches if you
have modifications that have worked for you. Or did you simply drop it in
and all we need to do is update the angular version in package.json?

**Comment by crazyabdul** [comment]
Yep! All you need to do is update the angular version and you are good to go. ;)

**Comment by sirkitree** [comment]
https://github.com/sirkitree/angular-directive.g-signin/commit/3f6c2f3e1ec609c857e4afa33ddc2b7069c49651
